---
title: "Youth"
author: "Thomas Scherer"
date: "September 13, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(magrittr)
```


```{r}
target_file <- paste0(here::here(),"/data/literature_datasheet.xlsx")

downloaded_file <- googledrive::drive_download(file="https://docs.google.com/spreadsheets/d/1VUqxkCno5NEKIIYLuqgXOEbJNo6Mi9Rl4MKO2_Pj_yg/edit#gid=0", path=target_file, type = "xlsx", overwrite=T)

datasheet_youth  <- readxl::read_excel(target_file, sheet="Youth") %>%
  janitor::clean_names() %>%
  dplyr::mutate(temp = NULL) %>%
 # janitor::remove_empty_rows() %>%
#  janitor::remove_empty_cols() %>%
  dplyr::mutate_all(as.character)

```

```{r}
datasheet_youth %>% dplyr::filter(!is.na(type)) %>% dplyr::select(type) %>% table()
```


```{r}

datasheet_youth %>% dplyr::filter(!is.na(type)) %>% dplyr::count(type, sort=TRUE) %>%
  kableExtra::kable(format = "html") %>%
  kableExtra::kable_styling() %>% 
  kableExtra::scroll_box(width = "100%", height = "200px")
```



```{r}

DT <- table(datasheet_youth$data_transparency)

barplot(DT, main="Data Transparency",
   xlab="rating")


```



```{r}



counts <- datasheet_youth %>% 
  dplyr::count(treatment_measure_rating) %>% dplyr::rename(score = treatment_measure_rating, treatment_measure_rating=n) %>% 
  dplyr::full_join(datasheet_youth %>% dplyr::count(outcome_measure_rating) %>% dplyr::rename(score = outcome_measure_rating, outcome_measure_rating=n)) %>% 
  dplyr::full_join(datasheet_youth %>% dplyr::count(explanatory_power) %>% dplyr::rename(score = explanatory_power, explanatory_power=n)) %>% 
  dplyr::full_join(datasheet_youth %>% dplyr::count(discussion_of_best_practice_and_program_guidelines) %>% dplyr::rename(score = discussion_of_best_practice_and_program_guidelines, discussion_of_best_practice_and_program_guidelines=n)) %>% 
  dplyr::full_join(datasheet_youth %>% dplyr::count(discussion_of_future_research_shortcomings) %>% dplyr::rename(score = discussion_of_future_research_shortcomings, discussion_of_future_research_shortcomings=n)) %>% 
  dplyr::full_join(datasheet_youth %>% dplyr::count(data_transparency) %>% dplyr::rename(score = data_transparency, data_transparency=n)) %>%
  dplyr::full_join(datasheet_youth %>% dplyr::count(analysis_replicability_methods_transparency) %>% dplyr::rename(score = analysis_replicability_methods_transparency, analysis_replicability_methods_transparency=n)) %>%
  dplyr::full_join(datasheet_youth %>% dplyr::count(ethical_considerations) %>% dplyr::rename(score = ethical_considerations, ethical_considerations=n))


```

```{r}
missingsum <- counts[5:7,] %>% dplyr::select(-score) %>% colSums(na.rm=TRUE)

counts_sum <- rbind(counts[1:4,], c("missing", missingsum))

transposed <- counts_sum %>%
   tidyr::pivot_longer(cols = -score, names_to = 'count', names_repair = "minimal") %>% 
   tidyr::pivot_wider(names_from = score, values_from = value)

```

```{r}
transposed %>%
  kableExtra::kable(format = "html") %>%
  kableExtra::kable_styling() %>% 
  kableExtra::scroll_box(width = "100%", height = "200px")
```



